# Generated by Django 5.2.12 on 2026-04-04 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_assigned_at_booking_completed_at_and_more'),
        ('services', '0007_service_pricing_type_service_starting_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_provider_response', 'Pending Provider Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('inspection_scheduled', 'Inspection Scheduled'), ('booking_created', 'Booking Created'), ('cancelled', 'Cancelled')], default='pending_provider_response', max_length=32)),
                ('provider_response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('preferred_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_service_requests', to='services.serviceprovider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='services.service')),
            ],
        ),
    ]
