# Generated by Django 5.2.12 on 2026-04-03 06:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_service_name'),
        ),
    ]
