# Generated by Django 5.2.12 on 2026-04-03 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def deduplicate_provider_services(apps, schema_editor):
    ServiceProvider = apps.get_model("services", "ServiceProvider")
    seen_pairs = {}

    for provider in ServiceProvider.objects.all().order_by("id"):
        key = (provider.user_id, provider.service_id)
        if key in seen_pairs:
            provider.delete()
            continue
        seen_pairs[key] = provider.id


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_unique_service_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('skills_summary', models.TextField(blank=True)),
                ('availability_notes', models.TextField(blank=True)),
                ('default_location', models.CharField(blank=True, max_length=120)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('is_accepting_jobs', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(deduplicate_provider_services, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='serviceprovider',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='unique_provider_service'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
