# Generated by Django 5.2.12 on 2026-04-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_providerprofile_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='is_active_provider',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
