# Generated by Django 5.2.12 on 2026-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_providerprofile_is_active_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('starting_from', 'Starting From'), ('inspection', 'Inspection Required'), ('custom_quote', 'Custom Quote')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='starting_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
